### ISSUE TITLE
issue with text overlap in options

### ISSUE THREAD

**Issue by doomedraven** [dracula/ida#5]
hello

<img width="692" alt="Screenshot 2022-02-22 at 08 50 44" src="https://user-images.githubusercontent.com/1856495/155086643-e02b696b-cae0-4374-bf70-a9f34644d91c.png">

tested with latest Version 7.7.220218 macOS x86_64 (32-bit address size) and previous 

any tip where to star digging to fix this? i will try later to check ida docs if there is something which qt part is that

thank you

**Comment by relative** [comment]
add to the end of theme.css, should make it look better
```css
QGroupBox::title {
  subcontrol-origin: margin;
  subcontrol-position: top left;
  left: 7px;
  padding: 0px 4px 0px 6px;
}
QTabBar::tab {
  padding: 4px
}
```

**Comment by doomedraven** [comment]
restarted ida, no changes, file was saved after add that

![Screenshot 2022-02-23 at 15 18 54](https://user-images.githubusercontent.com/1856495/155337326-75479aad-3fee-4749-a849-99499e394727.png)

**Comment by relative** [comment]
did you update the right file? the end of my dracula/theme.css before the other rules is 
```css
QTreeView::item:selected,
QListView::item:selected,
QTableView::item:selected
{
    background-color: #323544;
    color: #ddd;
}
```

if you did, try switching theme to dark then back to dracula
